---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 4b58f47be0377d837df6625a5958e9e073b17538
    app.quarkus.io/build-timestamp: 2021-12-21 - 16:28:09 +0000
  labels:
    app.kubernetes.io/name: customer-event-analysis
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: customer-event-analysis
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: customer-event-analysis
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 4b58f47be0377d837df6625a5958e9e073b17538
    app.quarkus.io/build-timestamp: 2021-12-21 - 16:28:09 +0000
  labels:
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: customer-event-analysis
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: customer-event-analysis
spec: {}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-java
spec:
  dockerImageRepository: fabric8/s2i-java
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 4b58f47be0377d837df6625a5958e9e073b17538
    app.quarkus.io/build-timestamp: 2021-12-21 - 16:28:09 +0000
  labels:
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: customer-event-analysis
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: customer-event-analysis
spec:
  output:
    to:
      kind: ImageStreamTag
      name: customer-event-analysis:1.0.0-SNAPSHOT
  source:
    dockerfile: |
      ####
      # This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode
      #
      # Before building the container image run:
      #
      # ./mvnw package -Pnative
      #
      # Then, build the image with:
      #
      # docker build -f src/main/docker/Dockerfile.native -t quarkus/customer-event-analysis .
      #
      # Then run the container using:
      #
      # docker run -i --rm -p 8080:8080 quarkus/customer-event-analysis
      #
      ###
      FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4
      WORKDIR /work/
      RUN chown 1001 /work \
          && chmod "g+rwX" /work \
          && chown 1001:root /work
      COPY --chown=1001:root target/*-runner /work/application

      EXPOSE 8080
      USER 1001

      CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
  strategy:
    dockerStrategy: {}
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 4b58f47be0377d837df6625a5958e9e073b17538
    app.quarkus.io/build-timestamp: 2021-12-21 - 16:28:09 +0000
  labels:
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: customer-event-analysis
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: customer-event-analysis
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: customer-event-analysis
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/commit-id: 4b58f47be0377d837df6625a5958e9e073b17538
        app.quarkus.io/build-timestamp: 2021-12-21 - 16:28:09 +0000
      labels:
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/name: customer-event-analysis
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: chaika/customer-event-analysis:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: customer-event-analysis
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - customer-event-analysis
        from:
          kind: ImageStreamTag
          name: customer-event-analysis:1.0.0-SNAPSHOT
      type: ImageChange
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 4b58f47be0377d837df6625a5958e9e073b17538
    app.quarkus.io/build-timestamp: 2021-12-21 - 16:28:09 +0000
  labels:
    app.kubernetes.io/name: customer-event-analysis
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: customer-event-analysis
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: customer-event-analysis
